### PR TITLE
dynamically create L1 config files.

### PR DESCRIPTION
**Pull request by chitrangpatel**
- We have one config file which tells us the status of the L1 nodes (ie. if we are using them for the pipeline)
    - 1 -- yes
    - 0 -- no
- Based on the available nodes we dynamically create config files.
    - Accounts for the rack in which the node belongs and assigns `eno1, eno2` vs `eno3, eno4` for all the addresses.
    - each available node is assigned 8 beams (incrementing) starting with `0` : `0-7`, `8-15` and so on.

### CODE REVIEW

**Comment by dstndstn** [comment]
Do you also need to set the output_devices based on whether it's a 6/7 or 8/9 subnet?  I thought I heard that only 2 of the frb-archiver mount points were mounted for each machine.

Other than that, looks good!

**Comment by chitrangpatel** [comment]
Oh yeah. I forgot about that. Thanks for reminding me. I'll fix it now.

**Comment by chitrangpatel** [comment]
Removed `frb-archiver-3/4` from the list.

**Comment by chitrangpatel** [comment]
Color Coded status:
 - Grey : Node not accessible.
 - Red : L1 crashed previously.
 - Yellow : Node idle (Node is on but L1 is not running)
 - Green: L1 running

The web app has been tested. We can successfully launch the L1 server on `rack D` but not the others due to a memory allocation error on them. 
screen shot 2018-06-06 at 3 04 07 pm

**Comment by chitrangpatel** [comment]
I was accidentally allotting 29G of memory while running bonsai's  `ups` config. When changed to 20G it works even if I revert the telescoping ring buffer sizes to original. The memory usage in this case is 122G allowing 4 G of free memory.

**Comment by chitrangpatel** [comment]
Upgraded the web app significantly (To check it out: go to `localhost:5120`).
 - User Accounts (default: `frb`, `flub raw burden`)
 - Turn On/Off a L1 Node (executes cctl power on/off/cycle from the head node)
 - Bootstrap included

Next items:
 - Set it up with Apache so that we don't have to set up a tunnel every time we want to operate L1.
      - It will run as a website on probably `frb.chimenet.ca` or some other name.
 - Feature to stop acquisition on selected beams.
 - Sign up for Monitoring (A schedule where people can sign up for monitoring the system).

**Comment by chitrangpatel** [comment]
screen shot 2018-07-10 at 4 33 49 pm

**Comment by dstndstn** [comment]
I believe this is all now long obsolete.

**Comment by dstndstn** [comment]
(reopen if I'm wrong!)

**Pull request closed without merging**
