### PR TITLE
Cleaned up the web app l1 config file.

### PR DESCRIPTION
**Pull request by chitrangpatel**

### CODE REVIEW

**Comment by chitrangpatel** [comment]
You can check out the new layout of the page here since I'm running the server on `cfdn9`:
`ssh -L 5120:cfdn9:5120 <username>@liberty.drao.nrc.ca`
`http://localhost:5120/l1-service`

**Comment by dstndstn** [comment]
The layout looks awesome!!

One thing I like to do is, instead of code like this,

+       current_rack = "A" if current_rack == "10" else current_rack
+        current_rack = "B" if current_rack == "11" else current_rack
+        current_rack = "C" if current_rack == "12" else current_rack
+        current_rack = "D" if current_rack == "13" else current_rack

I sometimes use a dict and make it a one-liner:

    current_rack = { '10': 'A', '11': 'B', '12': 'C', '13': 'D' }.get(current_rack, current_rack)

(the .get(x, x) means "look for key x, and if not found, return x")

Nice work!

**Comment by dstndstn** [comment]
Oh, I see that you just requested a review... hope it's okay that I went ahead and merged it!

**Comment by chitrangpatel** [comment]
That’s fine. Thanks. I’ll update your other suggestions as well.

**Pull request merged**
